name: Remote update execution
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            echo 'running script...'
            exec bash -l
            echo 'changing directory'
            cd /var/www/loganwoolf.dev
            echo 'fetching new code'
            git pull
            echo 'upgrade pnpm'
            pnpm install -g pnpm
            echo 'install packages'
            pnpm install
            echo 'build'
            pnpm build
            echo 'success!'
