name: Remote update execution
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            export PATH="$PATH:~/.local/share/pnpm"
            source ~/.bashrc
            cd /var/www/loganwoolf.dev
            git pull
            pnpm install -g pnpm
            pnpm -v
            pnpm install
            pnpm build
